
export const COLORS = {
    type:"light",
    primaryOrange:'#FF851B', 
    lightGrey:"#C0C0C0",
    secondaryIcon: 'white',
    green:'green',
    red:'red',
    searchIconColor:'black',
    primaryText: 'black',
    drawerGrey:"#787878",
    darkerOrange: '#f4511e',
    lighterOrange: 'orange',
    lighterGray:'#e0e0e0',
    lightGray:'#c4c4c4',
    menuIcon:'#FF851B',
    menuText:'#FF851B',
    menuContainer:'#fff',
    checkOrange:"#ffc757",
    primaryBackground: 'orange',
    headerPrimary: "#fff",
    primaryHeaderBackground: "#FF851B",
    secondaryBackground: '#fff',
    barColor:"#fff",
    barTextColor:'black',
    barExternalColor:'#FF851B',
    bottomButtonsBackground:"#eee",
    lineColor:'rgba(196, 196, 196,0.4)',
    blue:'#0e49b5'
  };
  